// ============================================
// AL-MATAR RENTALS — CAR DATA (baked in, no fetch needed)
// Works on file:// protocol — no local server required
//
// PRICING MODEL: With-driver only. hourlyRate × package hours = price.
// Packages offered: 5hr, 10hr, 12hr, 20hr, 24hr (full day).
// hourlyRate values below are PLACEHOLDERS — replace with real client rates.
//
// NOTE ON IMAGES: every car now has BOTH
//   - image  : a single string (used for card thumbnails / previews)
//   - images : an array of one or more strings (used for the fleet.html
//              gallery modal). Keeping these in sync avoids the old bug
//              where card thumbnails broke for cars that only had an array.
// ============================================

const CARS_DATA = [
  {
    "id": 1,
    "name": "Toyota Corolla",
    "type": "Sedan",
    "image": "images/car1/toyota-corolla-Altis.jpeg",
    "images": ["images/car1/toyota-corolla-Altis.jpeg"],
    "rating": 4.9,
    "avail": "Available",
    "availClass": "avail-yes",
    "badge": "Most Popular",
    "badgeClass": "badge-blue",
    "cat": ["all", "economy", "sedan", "driver"],
    "popular": 10,
    "fuel": "Petrol",
    "seats": "5 Seats",
    "ac": "AC",
    "music": "Aux / BT",
    "feats": [
      "Driver included",
      "City commutes",
      "Free cancellation",
      "Fuel efficient"
    ],
    "desc": "Karachi's most popular budget car. Fuel-efficient, fully AC, perfect for daily city commutes in Gulshan Iqbal and across Karachi.",
    "hourlyRate": 550
  },
  {
    "id": 2,
    "name": "Toyota Corolla Land-Cruiser",
    "type": "Sedan",
    "image": "images/car2/land-cruiser.jpeg",
    "images": ["images/car2/land-cruiser.jpeg"],
    "rating": 4.8,
    "avail": "Available",
    "availClass": "avail-yes",
    "badge": "",
    "badgeClass": "",
    "cat": ["all", "sedan", "driver"],
    "popular": 8,
    "fuel": "Petrol",
    "seats": "5 Seats",
    "ac": "AC",
    "music": "Sound System",
    "feats": [
      "Driver included",
      "Long trips",
      "Airport pickup",
      "Family trips"
    ],
    "desc": "Pakistan's most trusted sedan. Comfortable and reliable for family trips, corporate travel, and outstation journeys across Pakistan.",
    "hourlyRate": 1600
  },
  {
    "id": 3,
    "name": "Alto",
    "type": "Sedan",
    "image": "images/car3/car-img.jpeg",
    "images": ["images/car3/car-img.jpeg"],
    "rating": 4.7,
    "avail": "Available",
    "availClass": "avail-yes",
    "badge": "",
    "badgeClass": "",
    "cat": ["all", "economy", "sedan", "driver"],
    "popular": 7,
    "fuel": "Petrol",
    "seats": "5 Seats",
    "ac": "AC",
    "music": "None",
    "feats": [
      "Driver included",
      "City trips",
      "Comfortable ride"
    ],
    "desc": "Stylish and comfortable sedan ideal for daily commutes and city drives across Karachi. Smooth ride, great fuel economy.",
    "hourlyRate": 450
  },
  {
    "id": 4,
    "name": "Haval Jolion",
    "type": "Sedan",
    "image": "images/car4/car.jpeg",
    "images": ["images/car4/car.jpeg"],
    "rating": 4.9,
    "avail": "Available",
    "availClass": "avail-yes",
    "badge": "Hot",
    "badgeClass": "badge-blue",
    "cat": ["all", "sedan", "driver"],
    "popular": 9,
    "fuel": "Petrol",
    "seats": "5 Seats",
    "ac": "Premium AC",
    "music": "Premium Audio",
    "feats": [
      "Driver included",
      "Sporty look",
      "Events & weddings",
      "Premium interior"
    ],
    "desc": "Sleek sporty sedan that turns heads. Perfect for weddings, events, and corporate travel. Comes with premium audio and interior.",
    "hourlyRate": 1200
  },
  {
    "id": 5,
    "name": "Toyota Hilux Vigo",
    "type": "SUV",
    "image": "images/car5/car.jpeg",
    "images": ["images/car5/car.jpeg"],
    "rating": 4.9,
    "avail": "Available",
    "availClass": "avail-yes",
    "badge": "Premium",
    "badgeClass": "badge-gold",
    "cat": ["all", "suv", "driver"],
    "popular": 6,
    "fuel": "Petrol",
    "seats": "5 Seats",
    "ac": "Dual AC",
    "music": "Camera + Screen",
    "feats": [
      "Driver included",
      "Family & outstation",
      "Backup camera",
      "Touch screen"
    ],
    "desc": "Modern SUV with premium features \u2014 backup camera, touchscreen, dual AC. Perfect for family outings and highway travel.",
    "hourlyRate": 1100
  },
  {
    "id": 6,
    "name": "Toyota Yaris Sedan",
    "type": "SUV",
    "image": "images/car6/car.jpeg",
    "images": ["images/car6/car.jpeg"],
    "rating": 5.0,
    "avail": "Available",
    "availClass": "avail-yes",
    "badge": "Top Pick",
    "badgeClass": "badge-gold",
    "cat": ["all", "suv", "driver"],
    "popular": 5,
    "fuel": "Diesel",
    "seats": "7 Seats",
    "ac": "Dual AC",
    "music": "Camera + Screen",
    "feats": [
      "Driver included",
      "Corporate & trips",
      "7-seater",
      "Highway king"
    ],
    "desc": "The go-to 7-seater SUV for large families and corporate groups. Powerful diesel engine conquers outstation trips effortlessly.",
    "hourlyRate": 2000
  },
  {
    "id": 7,
    "name": "Toyota Prado",
    "type": "Luxury SUV",
    "image": "images/car7/car.jpeg",
    "images": ["images/car7/car.jpeg"],
    "rating": 5.0,
    "avail": "Available",
    "availClass": "avail-yes",
    "badge": "Luxury",
    "badgeClass": "badge-black",
    "cat": ["all", "luxury", "suv", "driver"],
    "popular": 4,
    "fuel": "Diesel",
    "seats": "7 Seats",
    "ac": "Dual AC",
    "music": "Sunroof + Screen",
    "feats": [
      "Driver included",
      "Chauffeur available",
      "VIP events",
      "Sunroof",
      "Premium leather"
    ],
    "desc": "Pure luxury for VIP occasions, weddings, and business executives. Sunroof, premium leather, chauffeur-driven for maximum comfort.",
    "hourlyRate": 1900
  },
  {
    "id": 8,
    "name": "Toyota Corolla (Facelift)",
    "type": "Sedan",
    "image": "./images/car8/corolla 1.jpg",
    "images": [
      "./images/car8/corolla 2.jpg"
    ],
    "rating": 4.5,
    "avail": "Available",
    "availClass": "avail-yes",
    "badge": "Best Value",
    "badgeClass": "badge-green",
    "cat": ["all", "economy", "sedan"],
    "popular": 8,
    "fuel": "Petrol",
    "seats": "4 Seats",
    "ac": "AC",
    "music": "Aux / BT",
    "feats": ["City commutes", "Free cancellation", "Fuel efficient", "AC included"],
    "desc": "Reliable and budget-friendly sedan, perfect for daily city commutes across Karachi.",
    "hourlyRate": 550
  },
  {
    "id": 9,
    "name": "Toyota Corolla (New Shape)",
    "type": "Sedan",
    "image": "https://drive.google.com/uc?export=view&id=1NOo4HuDX1KvMXkQlVI9Uh1IWv-GoJ_t0",
    "images": [
      "https://drive.google.com/uc?export=view&id=1NOo4HuDX1KvMXkQlVI9Uh1IWv-GoJ_t0",
      "https://drive.google.com/uc?export=view&id=1vfPlaH1WDzFsGYspgy412qxjPvN3a1XD"
    ],
    "rating": 5,
    "avail": "Available",
    "availClass": "avail-yes",
    "badge": "New",
    "badgeClass": "badge-orange",
    "cat": ["all", "economy", "sedan"],
    "popular": 10,
    "fuel": "Petrol",
    "seats": "4 Seats",
    "ac": "AC",
    "music": "Aux / BT",
    "feats": ["City commutes", "Free cancellation", "Fuel efficient", "AC included"],
    "desc": "Brand new Corolla in excellent condition, ideal for comfortable city rides in Karachi.",
    "hourlyRate": 550
  },
  {
    "id": 10,
    "name": "Haval H6",
    "type": "Luxury",
    "image": "https://drive.google.com/uc?export=view&id=1N3zmWzhLsWU_nzE41xYuW_yQzVD9RFf-",
    "images": [
      "https://drive.google.com/uc?export=view&id=1N3zmWzhLsWU_nzE41xYuW_yQzVD9RFf-",
      "https://drive.google.com/uc?export=view&id=1q4_3YbCAgb0kXrHL14BqbV_tvWFlN6qc",
      "https://drive.google.com/uc?export=view&id=11CdkYgo5PFCAeH-gb6_bit1gWCE0O6e0",
      "https://drive.google.com/uc?export=view&id=1Qu4R7o8DcABeSJh27Zox1qLYJ3GqaDAo",
      "https://drive.google.com/uc?export=view&id=1xYuPojVK-Gt5noq-OC7kw34cYE2vYk13"
    ],
    "rating": 4.9,
    "avail": "Available",
    "availClass": "avail-yes",
    "badge": "New",
    "badgeClass": "badge-orange",
    "cat": ["all", "suv", "luxury"],
    "popular": 9,
    "fuel": "Petrol",
    "seats": "7 Seats",
    "ac": "AC",
    "music": "Aux / BT",
    "feats": ["Premium comfort", "Long drives", "Free cancellation", "Spacious interior"],
    "desc": "Spacious 7-seater SUV with premium comfort, great for family outings and long drives.",
    "hourlyRate": 1200
  },
  {
    "id": 11,
    "name": "Toyota Yaris",
    "type": "Sedan",
    "image": "./images/car11/Toyota Yaris 1.jpg",
    "images": [
      "./images/car11/Toyota Yaris (2).jpg",
      "./images/car11/Toyota Yaris (3).jpg",
      "./images/car11/Toyota Yaris (4).jpg",
      "./images/car11/Toyota Yaris (5).jpg",

    ],
    "rating": 4.6,
    "avail": "Available",
    "availClass": "avail-yes",
    "badge": "Best Value",
    "badgeClass": "badge-green",
    "cat": ["all", "economy", "sedan"],
    "popular": 7,
    "fuel": "Petrol",
    "seats": "4 Seats",
    "ac": "AC",
    "music": "Aux / BT",
    "feats": ["City commutes", "Free cancellation", "Fuel efficient", "AC included"],
    "desc": "Smooth and stylish sedan, well-suited for both city commutes and short trips.",
    "hourlyRate": 550
  },
  {
    "id": 12,
    "name": "Honda BR-V (Premium)",
    "type": "Luxury",
    "image": "./images/car12/Honda BRV (3).jpg",
    "images": [
      "./images/car12/Honda BRV (2).jpg", 
      "./images/car12/Honda BRV (1).jpg", 
    ],
    "rating": 5,
    "avail": "Available",
    "availClass": "avail-yes",
    "badge": "New",
    "badgeClass": "badge-orange",
    "cat": ["all", "suv", "luxury"],
    "popular": 9,
    "fuel": "Petrol",
    "seats": "7 Seats",
    "ac": "AC",
    "music": "Aux / BT",
    "feats": ["Premium comfort", "Long drives", "Free cancellation", "Spacious interior"],
    "desc": "Spacious and comfortable 7-seater, perfect for family trips and group travel.",
    "hourlyRate": 1000
  },
  {
    "id": 13,
    "name": "Honda BR-V (Family)",
    "type": "Family",
    "image": "https://drive.google.com/uc?export=view&id=1iGbaWsXj3aDAHiUx1XDka4JQ81Amv1ZQ",
    "images": [
      "https://drive.google.com/uc?export=view&id=1iGbaWsXj3aDAHiUx1XDka4JQ81Amv1ZQ",
      "https://drive.google.com/uc?export=view&id=1ZHIxtZddZLmwp84VJIqWruVyR2YlQfrj",
      "https://drive.google.com/uc?export=view&id=1hK1_Qq96EbftpmOHlH3HcUzgfeWG0JeO",
      "https://drive.google.com/uc?export=view&id=1XrWbAzoMx_pmGXWZSyanbri9fLl1rEiZ",
      "https://drive.google.com/uc?export=view&id=1-EO6gMsC_q1_p4LGo41jRFRywZoDrIBI"
    ],
    "rating": 5,
    "avail": "Available",
    "availClass": "avail-yes",
    "badge": "New",
    "badgeClass": "badge-orange",
    "cat": ["all", "suv"],
    "popular": 8,
    "fuel": "Petrol",
    "seats": "7 Seats",
    "ac": "AC",
    "music": "Aux / BT",
    "feats": ["Family trips", "Spacious seating", "Free cancellation", "7-seater"],
    "desc": "A budget-friendly 7-seater option, ideal for family outings around Karachi.",
    "hourlyRate": 800
  },
  {
    "id": 14,
    "name": "Corolla X",
    "type": "Sedan",
    "image": "https://drive.google.com/uc?export=view&id=11r83akVK20H8pk0n0vgFmOpAqmObw-Lm",
    "images": [
      "https://drive.google.com/uc?export=view&id=11r83akVK20H8pk0n0vgFmOpAqmObw-Lm",
      "https://drive.google.com/uc?export=view&id=1aUI0eSvfnn1EXRykmRbRq2uEsPOXvGnT",
      "https://drive.google.com/uc?export=view&id=191QbjiwV1ApvGsQkTmzHcqX_9fdLghTY",
      "https://drive.google.com/uc?export=view&id=1QYOW4pPhLGEtT2YlTaFa2LFo6zajtvCO",
      "https://drive.google.com/uc?export=view&id=1QXM4Kk7LEG2gjCn-0_5Bth-5g2xkgXGT"
    ],
    "rating": 5,
    "avail": "Available",
    "availClass": "avail-yes",
    "badge": "Premium",
    "badgeClass": "badge-purple",
    "cat": ["all", "economy", "sedan"],
    "popular": 9,
    "fuel": "Petrol",
    "seats": "5 Seats",
    "ac": "AC",
    "music": "Aux / BT",
    "feats": ["Premium comfort", "Long drives", "Free cancellation", "Spacious interior"],
    "desc": "A premium sedan offering a refined ride with modern features across Karachi.",
    "hourlyRate": 550
  }
];